name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Install dependencies
      run: dotnet restore Src/couchbase-net-linq.sln
    - name: Build
      run: dotnet build --configuration Release --no-restore Src/couchbase-net-linq.sln
    - name: Test
      run: dotnet test --no-restore --verbosity normal Src/Couchbase.Linq.UnitTests/Couchbase.Linq.UnitTests.csproj
